spring:
  profiles:
    active: local #local,dev,real (구동환경)
    
  datasource: #DB 접속
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: user01
    password : 1234
    hikari: #커넥션풀
      connection-timeout: 30000 #클라이언트가 pool에 connection을 요청하는데 기다리는 최대시간을 설정. 30초
      maximum-pool-size: 10 #최대 커넥션 개수 설정
      max-lifetime: 1800000 #커넥션풀에서 살아있을 수 있는 커넥션의 최대 수명 시간. 1,800초(30분)
      
  messages: #메세지처리
    basename: messages.validation
    encoding: UTF-8
    
  devtools: #View reload
    livereload:
      enabled: true
   
    restart: #컨트롤러,모델단이 바뀌었을 때 프로젝트 재시작 설정(정확히 classpath에 있는 모든 파일)
      enabled: true
      
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html #templates 아래에 .html 확장자
    check-template-location: true
    enabled: true
    mode: HTML5 #mode는 있어도 되고 없어도 된다.
    cache: false #캐시 사용하지 않음. 새로고침하면 변경사항 바로 확인

mybatis: #이 형식만 지키면 자동스캔
  type-aliases-package: kr.spring.**.vo
  mapper-locations: kr/spring/**/dao/*.xml
  
logging:
  level:
    #root: error
    '[kr.spring]': debug

server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true #http 인토딩 지원을 활성화할지 여부
      force: true